# Default deny-all-ingress policy for the namespace.
# This policy blocks all incoming traffic to pods unless explicitly allowed by other policies.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: uber-service
spec:
  podSelector: {}  # Selects all pods in the namespace
  policyTypes:
    - Ingress