broker:
  replicaCount: 1

controller:
  replicaCount: 0

kraft:
  enabled: false

zookeeper:
  enabled: true

auth:
  enabled: false

kafka:
  listeners: PLAINTEXT://:9092,EXTERNAL://:9094
  advertisedListeners: PLAINTEXT://kafka.uber-service.svc.cluster.local:9092,EXTERNAL://192.168.178.93:9094
  listenerSecurityProtocolMap:
    PLAINTEXT: PLAINTEXT
    EXTERNAL: PLAINTEXT
  interBrokerListenerName: PLAINTEXT

externalAccess:
  enabled: true
  broker:
    service:
      type: LoadBalancer
      ports:
        external: 9094
      loadBalancerIPs:
        - 192.168.178.93
  autoDiscovery:
    enabled: false
