admin:
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: GRAFANA_ADMIN_PASSWORD

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
