# Helm chart metadata for deploying Kafka consumer services.
# This chart manages deployments, autoscaling, and configuration for consumer modules.
apiVersion: v2
name: kafka-consumer
description: A Helm chart for deploying Kafka consumer services
type: application
version: 0.1.0
appVersion: "1.0"