replicaCount: 1

image:
  repository: uber-consumer
  tag: latest
  pullPolicy: Never

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "250m"

envFrom:
  configMapRef: common-env
  secretRef: postgres-secret

env:
  - name: KAFKA_BROKER
    value: kafka.uber-service.svc.cluster.local:9092
  - name: SCHEMA_REGISTRY_URL
    value: http://schema-registry.uber-service.svc.cluster.local:8081
  - name: POSTGRES_HOST
    value: postgres.uber-service.svc.cluster.local
  - name: POSTGRES_PORT
    value: "5432"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90