# Default values for the kafka-consumer Helm chart.
# These values configure image, resources, environment, and HPA for all consumers.

replicaCount: 1

image:
  repository: uber-consumer   # Docker image repository for the consumer
  tag: latest                # Image tag to deploy
  pullPolicy: Never          # Image pull policy

resources:
  requests:
    memory: "128Mi"          # Minimum memory request per pod
    cpu: "100m"              # Minimum CPU request per pod
  limits:
    memory: "512Mi"          # Maximum memory limit per pod
    cpu: "500m"              # Maximum CPU limit per pod

envFrom:
  configMapRef: common-env   # Reference to ConfigMap for environment variables
  secretRef: postgres-secret # Reference to Secret for sensitive environment variables

env:
  # Common environment variables for all consumers
  - name: KAFKA_BROKER
    value: kafka.uber-service.svc.cluster.local:9092
  - name: SCHEMA_REGISTRY_URL
    value: http://schema-registry.uber-service.svc.cluster.local:8081
  - name: POSTGRES_HOST
    value: postgres.uber-service.svc.cluster.local
  - name: POSTGRES_PORT
    value: "5432"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75