replicaCount: 1

image:
  repository: uber-consumer
  tag: latest
  pullPolicy: Never

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "250m"

envFrom:
  configMapRef: common-env
  secretRef: postgres-secret

env: []

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90