---
# Template for one Kafka consumer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-ride-requested
  namespace: uber-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-ride-requested
  template:
    metadata:
      labels:
        app: consumer-ride-requested
    spec:
      containers:
        - name: consumer-ride-requested
          image: uber-consumer:latest
          imagePullPolicy: Never
          command: ["python", "-m", "consumers.modules.consumers.consumer_ride_requested"]
          envFrom:
            - configMapRef:
                name: common-env
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-ride-started
  namespace: uber-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-ride-started
  template:
    metadata:
      labels:
        app: consumer-ride-started
    spec:
      containers:
        - name: consumer-ride-started
          image: uber-consumer:latest
          imagePullPolicy: Never
          command: ["python", "-m", "consumers.modules.consumers.consumer_ride_started"]
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-ride-completed
  namespace: uber-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-ride-completed
  template:
    metadata:
      labels:
        app: consumer-ride-completed
    spec:
      containers:
        - name: consumer-ride-completed
          image: uber-consumer:latest
          imagePullPolicy: Never
          command: [ "python", "-m", "consumers.modules.consumers.consumer_ride_completed" ]
          envFrom:
            - configMapRef:
                name: common-env
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-location-update
  namespace: uber-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-location-update
  template:
    metadata:
      labels:
        app: consumer-location-update
    spec:
      containers:
        - name: consumer-location-update
          image: uber-consumer:latest
          imagePullPolicy: Never
          command: ["python", "-m", "consumers.modules.consumers.consumer_location_update"]
          envFrom:
            - configMapRef:
                name: common-env
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-dlq
  namespace: uber-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-dlq
  template:
    metadata:
      labels:
        app: consumer-dlq
    spec:
      containers:
        - name: consumer-dlq
          image: uber-consumer:latest
          imagePullPolicy: Never
          command: ["python", "-m", "consumers.modules.consumers.consumer_dlq"]
          envFrom:
            - configMapRef:
                name: common-env
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-ride-requested-hpa
  namespace: uber-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-ride-requested
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-ride-started-hpa
  namespace: uber-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-ride-started
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-ride-completed-hpa
  namespace: uber-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-ride-completed
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-location-update-hpa
  namespace: uber-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-location-update
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-dlq-hpa
  namespace: uber-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-dlq
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75